// Generated by CoffeeScript 1.10.0
(function() {
  var a;

  a = "_   _       _                 _\n| | | |_ __ | | ___   __ _  __| |___\n| | | | '_ \\| |/ _ \\ / _` |/ _` / __|\n| |_| | |_) | | (_) | (_| | (_| \\__ \\\n\\___/| .__/|_|\\___/ \\__,_|\\__,_|___/\n     |_|";

  console.log(a);

}).call(this);

//# sourceMappingURL=test.js.map
